### ISSUE TITLE
代码块更换为等宽字体

### ISSUE THREAD

**Issue by MrZLeo** [QMHTMY/RustBook#1]
等宽字体便于代码阅读

**Comment by QMHTMY** [comment]
多谢，已更新为等宽字体 Source Code Pro.

**Comment by MrZLeo** [comment]
更换字体后的新文件似乎中文无法显示？

**Comment by QMHTMY** [comment]
我的打开没有问题，你看看时不是你的阅读器有什么问题。
![屏幕截图](https://user-images.githubusercontent.com/20437653/152666598-1a25ff13-5d54-474b-897a-383e98b0cf65.png)

**Comment by MrZLeo** [comment]
> 我的打开没有问题，你看看是不是你的阅读器有什么问题？
> ![屏幕截图](https://user-images.githubusercontent.com/20437653/152666598-1a25ff13-5d54-474b-897a-383e98b0cf65.png)

本地打开没有问题，GitHub在线浏览时中文看不见
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/25260092/152666707-08b2c4e6-c0ce-43c8-a438-f9697de74c9b.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/25260092/152666711-9a9b5ca9-df2e-4d87-8300-fd06c566ea9d.png">

**Comment by QMHTMY** [comment]
居然还有这种问题？估计是 Github 渲染出问题了，我去了解一下。

**Comment by QMHTMY** [comment]
渲染问题解决了，同时更新了一波，封面和内容都有调整。
