### ISSUE TITLE
PDF文件字体大小

### ISSUE THREAD

**Issue by ocfox** [QMHTMY/RustBook#12]
我想在电子阅读器上阅读本书，但是pdf文件很难重新编辑改变字体大小。
麻烦可以提供一个字体更大的版本吗？（如果可以的话
如果转换格式的话会对阅读有很大的影响。
谢谢。

**Comment by QMHTMY** [comment]
字体目前是 10pt，按出版社要求会改成 11.5 pt，更新了通知你。

**Comment by ocfox** [comment]
xp xp
