### ISSUE TITLE
Some typos to be corrected

### ISSUE THREAD

**Issue by sukanka** [QMHTMY/RustBook#14]
简中版 3.6.2 节 59页有 typo
![image](https://user-images.githubusercontent.com/31362108/178779490-83756ac8-c010-4e87-843c-4d58adc75fed.png)
高亮部分应为 `IntoIter`

Section 5.5.1 哈希函数
> 分组求和法可以求哈希值，平法取中法也可以，这是另一种哈希算法。

此处 **平法取中法** 应为 **平方取中法**

**Comment by sukanka** [comment]
另外，部分公式里面的函数名称建议使用 直立体， 如 
使用 $\log(n)$ (`$\log(n)$`) 而不是 $log(n)$ (`$log(n)$`), 
使用 $\mathrm{hash}(n)$ (`$\mathrm{hash}(n)$`) 而不是 $hash(n)$ (`$hash(n)$`)， 
还有 $\mathrm{O}(n)$ (`$\mathrm{O}(n)$`) 而不是 $O(n)$ (`$O(n)$`)
![image](https://user-images.githubusercontent.com/31362108/179233297-511a96a5-b5ca-4e0f-9a88-55eaa91bb76e.png)

**Comment by QMHTMY** [comment]
感谢，我将抽时间更正此开源版本。本书有出版社准备出版了，我重写并增加了非常多内容，代码也大幅优化过，到时候欢迎阅读。

**Comment by sukanka** [comment]
新增一处 p154,
![image](https://user-images.githubusercontent.com/31362108/184907907-a42bf622-bb43-47ab-a47a-6614099f6892.png)

```rust
fn get_exp<T: Clone + Debug + Display>(bt: Link<T>) -> Sring {
```
这里 `Sring` 应为 `String`, [仓库里对应的代码](https://github.com/QMHTMY/RustBook/blob/main/code/chapter07/binary_tree.rs)没有问题

**Comment by sukanka** [comment]
7.5 平衡二叉树 p177 
如下语句不通顺。

> AVL 树的是普通二叉查找树,唯一区别是树的操作执行方式。

**Comment by sukanka** [comment]
7.5.1 AVL 平衡二叉树 p178
斐波那契数列 $F_0$ 的值应为1,否则 $N(h)=F(h+2)-1$ 的关系式不能成立。
举例：按图里的计算
$N(0)=1$, $F(2)=F(0)+F(1)=1$, $N(0) \neq F(2)-1$
![image](https://user-images.githubusercontent.com/31362108/185050479-d3ad18e6-3dce-4b26-b129-b92416322476.png)

**Comment by sukanka** [comment]
## 8.5.1 图解决字梯问题 p202

代码 typo:  （仓库里的代码已修正。）
在 `// word_lader.rs` 中
函数签名应为
```rust
- fn build_word_graph(words: &[String]) -> Graph {
+ fn build_word_graph(words: &[String]) -> Graph<String> {
```
```diff
- d.get_mut(&bucket).unwra().push(wd);
+ d.get_mut(&bucket).unwrap().push(wd);
```
![image](https://user-images.githubusercontent.com/31362108/185176391-9c040d38-92db-4249-b697-5caa1c458317.png)
