### ISSUE TITLE
`heap_sort` 结果异常

### ISSUE THREAD

**Issue by sukanka** [QMHTMY/RustBook#15]
使用的代码为 https://github.com/QMHTMY/RustBook/blob/8c6ef29bc84672e37ca4d6b90aafccba10e9b6da/code/chapter06/heap_sort.rs
其中， `main` 函数略有不同 （删掉 `nums` 开头的 `0`）
```rust
fn main() {
    let mut nums = [ 54, 32, 99, 18, 75, 31, 43, 56, 21, 22];
    heap_sort(&mut nums);
    println!("sorted nums: {:?}", nums);
}
```
输出结果为
```
sorted nums: [54, 18, 21, 22, 31, 32, 43, 56, 75, 99]
```
期望的结果为
```
sorted nums: [18, 21, 22, 31, 32, 43, 54, 56, 75, 99]
```

**Comment by QMHTMY** [comment]
用这个代码试试：https://github.com/QMHTMY/RustBook/blob/main/publication/code/chapter07/heap_sort.rs
