### ISSUE TITLE
p175 图示有误

### ISSUE THREAD

**Issue by sukanka** [QMHTMY/RustBook#16]
7.4.2 Rust 实现二叉查找树 p175
 二叉查找树删除节点的图示有误。
![image](https://user-images.githubusercontent.com/31362108/185038695-e513b7d3-5119-4359-8cfa-c7d3b77b6be1.png)
这幅图删除了 93 之后应该是 76 或者 94 代替 93 的位置吧。 图示的结果不满足 p168 说的要求。
> 不同于堆的左右子节点不考虑大小关系,二叉查找树左子节点键要小于父节点的键,右
子节点的键要大于父节点键。也就是 left < parent < right 这个规律,其递归地适用于所有
子树。

**Comment by sukanka** [comment]
## 8.2.1 图定义 p190
边集合 $E$ 有误，边的权重很多不是5.
另外，集合是否应该用 集合符号 `{}` 呢，如
$V = \\{V0, V1, V2, V2, V4, V5\\}$ 对应 latex 代码 `V = \{V0, V1, V2, V2, V4, V5\}`

![image](https://user-images.githubusercontent.com/31362108/185103367-60b525f6-fed9-41c5-9fcc-efb5fb3b2c03.png)

**Comment by QMHTMY** [comment]
ok，第一个问题已经改了，第二个问题得改下，但目前本书已经出版了(https://www.epubit.com/bookDetails?id=UB8316fd0fcc787&typeName=)，只能在第二版改。目前的开源版和出版物差40%的内容，有兴趣可以买来看下，很多算法都已经修改和实现了。当然不买也是没问题的，感谢您持续对本书提出意见，如果有第二版，我将把您的名字列到致谢里去。
