### ISSUE TITLE
英文版代码和中文版不一样

### ISSUE THREAD

**Issue by sigpher** [QMHTMY/RustBook#19]
书写得挺好的，不过偶然发现英文版和中文版同样的内容会出现不一样的代码

**Comment by QMHTMY** [comment]
可以截图举例哈，应该是有部分代码更新过了，所以存在不一致。中文版开源的已经落后了(由于版权问题，中文版无法再更新了)，英文版是最新的，和最近出版的中文版基本是一样的。
