### ISSUE TITLE
Code typo in Chapter 1.4 Review 

### ISSUE THREAD

**Issue by YuyangXueEd** [QMHTMY/RustBook#22]
Hi, thank you very much for your wonderful book. I learnt a lot.

I found an error in the English version of book, page 9 top, where you define array here:
```
// [type; num] define array
let digits[i32; 5] = [0, 1, 2, 3, 4]
```
However, I got the error when I compiled it:
```
error: expected one of `:`, `;`, `=`, `@`, or `|`, found `[`                                              
  --> src/main.rs:23:15
   |
23 |     let digits[i32; 5] = [0, 1, 2, 3, 4];
   |               ^ expected one of `:`, `;`, `=`, `@`, or `|`
```

I think it should be
```
// [type; num] define array
    let digits: [i32; 5] = [0, 1, 2, 3, 4];
```

My rust version is `rsutc 1.79.0`. I just start learning so let me know if it is right or wrong. Thank you very much.

**Comment by QMHTMY** [comment]
Yes, you're right. I've fixed that mistake.
