### ISSUE TITLE
Chinese characters could not be loaded in pdf

### ISSUE THREAD

**Issue by nicemayi** [QMHTMY/RustBook#7]
Hi Shieber, thanks for the book! However, it appears that the pdf could not be loaded/rendered on web browser (specifically Chrome that I'm currently using), any plan to fix that (by the way the download version is perfect) ?

Thanks!

**Comment by QMHTMY** [comment]
Ok, I will  find the reason and solve this problem as soon as possible.

**Comment by QMHTMY** [comment]
https://support.github.com/ticket/personal/0/1517391
